name: Build osquery on Windows

on:
  push:
    branches:
      - main  # Adjust this branch name to match your default branch

jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Use the appropriate Python version

    - name: Install Visual Studio Build Tools
      run: |
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Workload.MSBuildTools --add Microsoft.VisualStudio.Component.VC.14.28.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK.19041 --add Microsoft.VisualStudio.Component.VC.ClangToolset --add Microsoft.VisualStudio.Workload.NetCoreBuildTools --add Microsoft.VisualStudio.Component.NuGet.Packaging --add Microsoft.VisualStudio.Component.TextTemplating --add Microsoft.VisualStudio.Component.Wix.Toolset --add Microsoft.VisualStudio.Component.Windows10SDK.19041"
      env:
        chocolateyBeforePath: true  # Make sure Chocolatey is in PATH

    - name: Set Visual Studio Environment Variables
      run: |
        $env:VSINSTALLDIR = 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools'
      shell: cmd

    - name: Download and Build Source
      run: |
        # Clone the osquery repository
        git clone https://github.com/osquery/osquery
        cd osquery

        # Configure
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_GENERATOR_PLATFORM=x64 ..

        # Build
        cmake --build . --config RelWithDebInfo -j10  # Number of projects to build in parallel
