name: build_windows

on:
  push:
    branches:
      - main

jobs:
  build_windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_type: [Release]
        bitness: [64, arm64]
        os: [windows-2019]

    steps:
      - name: Setup the build paths
        shell: powershell
        id: build_paths
        run: |
          $rel_src_path = "w\\src"
          $rel_build_path = "w\\build"
          $rel_srcache_path = "w\\sccache"
          $rel_downloads_path = "w\\downloads"
          $rel_install_path = "w\\install"
          $rel_packaging_data_path = "w\\packaging_data"
          $rel_packaging_path = "w\\osquery-packaging"

          New-Item -ItemType Directory -Force -Path $rel_build_path
          New-Item -ItemType Directory -Force -Path $rel_srcache_path
          New-Item -ItemType Directory -Force -Path $rel_downloads_path
          New-Item -ItemType Directory -Force -Path $rel_install_path
          New-Item -ItemType Directory -Force -Path $rel_packaging_data_path


          $base_dir = (Get-Item .).FullName

          echo "SOURCE = $base_dir\$rel_src_path" >> $env.GITHUB_OUTPUT

          
          
