name: build
on: [pull_request]
jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install -y python3 --params "/InstallDir:C:\Python37"
          choco install -y git
          choco install -y visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
      - name: Configure osquery
        run: |
          git clone https://github.com/osquery/osquery
          cd osquery
          mkdir build
          cd build
          cmake -G "Visual Studio 16 2019" -A x64 ..
      - name: Build osquery
        run: |
          cd build
          cmake --build . --config Release --target osqueryd osqueryi
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: osquery-windows-binaries
          path: build\osquery\Release\osqueryd.exe, build\osquery\Release\osqueryi.exe

